CC=clang
CFLAGS=-Wall -pedantic
INCLUDE=-I/usr/local/include
LIBS=-L/usr/local/lib -lcmocka

all:	blockchain_test \
	socket_test

blockchain_test:	
	$(CC) $(CFLAGS) $(INCLUDE) $(LIBS) -lcrypto blockchain_test.c ../blockchain.c -o blockchain_test

socket_test:
	$(CC) $(CFLAGS) $(INCLUDE) $(LIBS) socket_test.c ../socket.c -o socket_test

clean:
	rm blockchain_test
	rm socket_test
