CC=clang
CFLAGS=-Wall -pedantic
INCLUDE=-I"c:\Program Files\OpenSSL-Win64\include" -I"c:\cmocka-1.1.0\include"
LIBS=-L"c:\Program Files\OpenSSL-Win64\lib" -L"c:\cmocka-1.1.0\lib" -llibcrypto -lcmocka -lws2_32 -liphlpapi

all:	blockchain_test \
	socket_test \
	network_test

blockchain_test:	blockchain_test.c ../blockchain.c
	$(CC) $(CFLAGS) $(INCLUDE) blockchain_test.c ../blockchain.c $(LIBS) -o blockchain_test

socket_test:  		socket_test.c ../socket.c
	$(CC) $(CFLAGS) $(INCLUDE) socket_test.c ../socket.c $(LIBS) -o socket_test

network_test:		network_test.c ../socket.c ../net.c
	$(CC) $(CFLAGS) $(INCLUDE) network_test.c ../socket.c ../net.c $(LIBS) -o network_test

clean:
	del blockchain_test
	del socket_test
	del network_test
