CC=clang
CFLAGS=-Wall -pedantic -g
INCLUDE=
LIBS=-lcmocka

all:	blockchain_test

blockchain_test:	blockchain_test.c ../blockchain.c 
	$(CC) $(CFLAGS) $(INCLUDE) $(LIBS) -lcrypto blockchain_test.c ../blockchain.c -o blockchain_test

clean:
	rm blockchain_test
	
