CC=clang
CFLAGS=-Wall -pedantic
INCLUDE=-I/usr/local/include
LIBS=-L/usr/local/lib -lcmocka

all:	blockchain_test 
	

blockchain_test:	blockchain_test.c ../blockchain.c	
	$(CC) $(CFLAGS) $(INCLUDE) $(LIBS) -lcrypto blockchain_test.c ../blockchain.c -o blockchain_test

clean:
	rm blockchain_test

