CC=clang
OBJECTS=main.o socket.o net.o ipc.o blockchain.o firewall.o
CFLAGS=-Wall -pedantic --std=c99 -O3 -c
INCLUDE=-I"c:\Program Files\OpenSSL-Win64\include" -I"win32\include"
LIBS=-L"c:\Program Files\OpenSSL-Win64\lib" -L"win32\lib" -llibcrypto -lWs2_32 -liphlpapi -lpthreadVC2

dfw:	$(OBJECTS)
	$(CC) $(INCLUDE) -o dfw.exe $(OBJECTS) $(LIBS)
	copy win32\dll\pthreadVC2.dll .

%.o:	%.c
	$(CC) $(CFLAGS) $(INCLUDE) $< -o $@

clean:
	del *.o
	del dfw.exe

