CC=clang
OBJECTS=main.o socket.o net.o ipc.o blockchain.o firewall.o
CFLAGS=-Wall -pedantic -c -O3 -std=c89
INCLUDE=-I/usr/pkg/include
LIBS=-L/usr/pkg/lib -lrt -lcrypto

dfw:	$(OBJECTS)
	$(CC) $(INCLUDE) -o dfw $(OBJECTS) $(LIBS)

%.o:	%.c
	$(CC) $(CFLAGS) $(INCLUDE) $< -o $@

clean:
	rm *.o
	rm dfw
