CC=clang
CFLAGS=-Wall -pedantic
INCLUDE=
LIBS=-lcmocka -lcrypto
SRCS=main.c net.c socket.c blockchain.c 

all:	main

main:	$(SRCS)
	$(CC) $(CFLAGS) $(INCLUDE) -o main $(LIBS) $(SRCS)

clean:
	rm main
