CC=clang
OBJECTS=main.o socket.o net.o ipc.o blockchain.o
CFLAGS=-Wall -pedantic --std=c99 -O3 -c
INCLUDE=-I"c:\Program Files\OpenSSL-Win64\include" -I"c:\cmocka-1.1.0\include"
LIBS=-L"c:\Program Files\OpenSSL-Win64\lib" -L"c:\cmocka-1.1.0\lib" -llibcrypto -lWs2_32 -liphlpapi

dfw:	$(OBJECTS)
	$(CC) $(INCLUDE) -o dfw.exe $(OBJECTS) $(LIBS)

%.o:	%.c
	$(CC) $(CFLAGS) $(INCLUDE) $< -o $@

clean:
	del *.o
	del dfw.exe

