CC=clang
OBJECTS=main.o socket.o net.o ipc.o blockchain.o firewall.o
CFLAGS=-Wall -pedantic --std=c89 -O3 -c -D_XOPEN_SOURCE=500
INCLUDE=-I/usr/local/include
LIBS=-L/usr/local/lib -lrt -lcrypto -lpthread

dfw:	$(OBJECTS)
	$(CC) -o dfw $(OBJECTS) $(LIBS)

%.o:	%.c
	$(CC) $(CFLAGS) $(INCLUDE) $< -o $@

clean:
	rm *.o
	rm dfw
