CC=clang
CFLAGS=-Wall -pedantic
INCLUDE=-I/usr/pkg/include
LIBS=-L/usr/pkg/lib -lcmocka
SRCS=main.c net.c socket.c blockchain.c 

all:	main

main:	$(SRCS)
	$(CC) $(CFLAGS) $(INCLUDE) -o main $(LIBS) $(SRCS)

clean:
	rm main
